### PR TITLE
Remove dependency on <algorithm> by introducing nda::internal::{min, max}

### PR DESCRIPTION
**Pull request by fbleibel-g**

### CODE REVIEW

**Comment by fbleibel-g** [comment]
I replace std::min with internal::min (where not already in 'namespace internal'). I'm not sure how to trigger Travis CI prior to submitting for review the PR, so I'll wait for travis to complete.

**Comment by dsharlet** [comment]
Thanks for doing this! It looks good, but there is one small issue: I already merged your PR to add the `<algorithm>` include. Can you merge master, and remove that include in this PR?

**Comment by dsharlet** [comment]
BTW, if you want to run the travis build manually, it is here: https://github.com/dsharlet/array/blob/master/.travis.yml#L12-L16. Personally, I only run `make test` for most work unless I have a particular reason to want the extra test coverage.

**Comment by fbleibel-g** [comment]
Of course, no problem. I have rebased on HEAD and the change now removes <algorithm> - good catch.

**Pull request merged**
